### ISSUE TITLE
Bug: isHydrated() remains true even after reset()

### ISSUE THREAD

**Issue by starfishpatkhoo** [flightphp/active-record#10]
I think isHydrated() should be cleared when we reset()

```php
$user->find();
echo $user->isHydrated() ? "Yes" : "No";  // Yes
echo $user->name;  // "John Doe"
$user->reset();
echo $user->isHydrated() ? "Yes" : "No";  // Yes
var_dump($user->name);  // NULL
var_dump($user->toArray());  // array(0){}
```

**Comment by n0nag0n** [comment]
That prob needs to be tweaked as well! If you want an easy PR opportunity, this is your moment ;) haha

**Comment by starfishpatkhoo** [comment]
> That prob needs to be tweaked as well! If you want an easy PR opportunity, this is your moment ;) haha

Ha ha ha ! Let me hit my deadline first.. Then I can come back and look at this.. ^_^

**Comment by n0nag0n** [comment]
https://github.com/flightphp/active-record/commit/e90cf11cf2d844701827788bd417a8f3545b3155 No worries, I gotcha covered. I'll release this soon, but you can use the dev-master if you need to

**Comment by starfishpatkhoo** [comment]
Thanks man.. will check it out.. I need to hit my project deadline first..

**Comment by n0nag0n** [comment]
Good luck meeting your deadlines!
