### ISSUE TITLE
Suggestion: Add a table_name parameter to WHERE conditions

### ISSUE THREAD

**Issue by starfishpatkhoo** [flightphp/active-record#11]
I love the where conditions because it makes the query code so much easier to read. A single authorisation check joins 3 tables with conditions on two fields, sort order, blah blah.. Such a pain to read (and debug).

I wanted to `->eq("other_table.field", "value")` but it becomes `mytable.other_table.field` in SQL .. So I have to write the `->where()` by hand.. ha ha.. 

So if `->eq()` and friends can either have an optional third param being the table name, or become smart enough not to insert the table name automatically when it has already been specified.. that would eliminate another big use of `->where()` and `->pdo->quote()` ...

Yes, I am a spoiled brat. 🤣

**Comment by n0nag0n** [comment]
Well I'm curious....if you are specifying another table in your where statement, how are you writing your joins? I guess you would need to escape that as well if you're writing it in the join...not sure how, but I think I could scan for a `.` in the `eq()` and if it's there do not add the table name.

**Comment by starfishpatkhoo** [comment]
> Well I'm curious....if you are specifying another table in your where statement, how are you writing your joins? I guess you would need to escape that as well if you're writing it in the join...not sure how, but I think I could scan for a `.` in the `eq()` and if it's there do not add the table name.

Oh just normal join with `->join()` .. 

```php
$db = new mytable;
$db->join("table2", "mytable.key = table2.key");
$db->join("table3", "mytable.key = table3.key");
$db->eq("table2.field", "data1");
$db->eq("table3.field", "data2");
$db->order("table3.date");
$db->find();
```

so if using where..

```php
$db = new mytable;
$db->join("table2", "mytable.key = table2.key");
$db->join("table3", "mytable.key = table3.key");
$db->where("table2.field = data1 and table3.field = data2");
$db->order("table3.date");
$db->find();
```

Then have to escape and blah blah the data. .. 

Something like that. The point is, it is much easier to read and understand now, so it really is nice.. Leave the where for the really complicated with multiple groups ( ) and such. Ha ha ..

**Comment by n0nag0n** [comment]
I believe this PR addresses what you're after. Check the new version! https://github.com/flightphp/active-record/pull/16

**Comment by starfishpatkhoo** [comment]
Sorry, just now managing to have a look, seems to be working great, thank you! ^_^
