### ISSUE TITLE
Bug: beforeUpdate & beforeSave event is not working

### ISSUE THREAD

**Issue by Billtec** [flightphp/active-record#12]
Just curious why the following examples listed in [FlightPHP official docs](https://docs.flightphp.com/awesome-plugins/active-record) is not working as expected.

**beforeSave(ActiveRecord $ActiveRecord)/afterSave(ActiveRecord $ActiveRecord)**
This is useful if you want events to happen both when inserts or updates happen. I'll spare you the long explanation, but I'm sure you can guess what it is.

```
class User extends flight\ActiveRecord {

    public function __construct($database_connection)
    {
        parent::__construct($database_connection, 'users');
    }

    protected function beforeSave(self $self) {
        $self->last_updated = gmdate('Y-m-d H:i:s');
    } 
}
```

**Comment by Billtec** [comment]
Spend some time to read the codes and found the solution. @n0nag0n please check the PR.

**Comment by n0nag0n** [comment]
Thanks so much for the help! I realized after working on it some more, there were some other flawed pieces of logic to work out. https://github.com/flightphp/active-record/pull/14
