### ISSUE TITLE
Error when doing 2 joins in a row from one class

### ISSUE THREAD

**Issue by jsantari** [flightphp/active-record#19]
I have a users class with two functions which both use a join. When I run the second function the join statements get added in twice creating an error with the sql. I've poked around enough to enable the line in buildSql() to show the statements generated.

Here are the two statements that are generated. The only difference in the code is to select either by users_id or by groups_id,

The first one from this code.
$res = $this->select('*')->join('users', 'users.id=users_groups.users_id')->join('groups','groups.id=users_groups.groups_id')->eq('users_id', $id)->findAll();

Generates this:

SELECT * FROM users_groups LEFT JOIN users ON users.id=users_groups.users_id LEFT JOIN groups ON groups.id=users_groups.groups_id WHERE users_groups.users_id = 1 

Here is what happens with the second one.
$res = $this->select('*')->join('users', 'users.id=users_groups.users_id')->join('groups','groups.id=users_groups.groups_id')->eq('groups_id', $id)->findAll();

Generates this:

SELECT * FROM users_groups LEFT JOIN users ON users.id=users_groups.users_id LEFT JOIN groups ON groups.id=users_groups.groups_id LEFT JOIN users ON users.id=users_groups.users_id LEFT JOIN groups ON groups.id=users_groups.groups_id WHERE users_groups.groups_id = 1 

I've determined that the if the $join variable gets reset prior to running the second one things are ok.

**Comment by n0nag0n** [comment]
Hmm lots of good detective work in there. I think you might be right, let me check over the code and see if it makes sense to reset that $join variable.

**Comment by n0nag0n** [comment]
Yup, you were right! And just a call out here that unit tests are amazing XD. I was able to quickly add a unit test to replicate the bad behavior and then test the fix against all other tests and it worked like a charm! I've added a new release with the new bugfix. I probably should have waited to verify that the fix actually fixes your problem :laughing:

**Comment by jsantari** [comment]
Works great!

**Comment by n0nag0n** [comment]
Glad to hear! Thanks for the help!
