### ISSUE TITLE
Can you add a method to obtain sql?

### ISSUE THREAD

**Issue by SyanH** [flightphp/active-record#6]
In some cases, you need to view the generated sql for debugging.
Thanks！

**Comment by n0nag0n** [comment]
Hey there....sorry for some reason I was set to not get any notifications :man_shrugging: 

So for now, what you actually could do is installed Tracy and then there's the https://github.com/flightphp/tracy-extensions that you could install which would provide a debugging panel to see all the queries executing on a page load. Super helpful. There's more info in the [docs](https://docs.flightphp.com/awesome-plugins/tracy-extensions)

**Comment by SyanH** [comment]
Thanks

**Comment by n0nag0n** [comment]
I ended up adding this anyway with another issue I needed to fix. https://github.com/flightphp/active-record/releases/tag/v0.4.1 After running your find/update method, you can capture the query with `$YourRecord->getBuiltSql()`
